# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_site_interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 450)
        MainWindow.setMinimumSize(QtCore.QSize(400, 450))
        MainWindow.setMaximumSize(QtCore.QSize(400, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 10, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LabelNameSite = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelNameSite.setFont(font)
        self.LabelNameSite.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNameSite.setObjectName("LabelNameSite")
        self.horizontalLayout.addWidget(self.LabelNameSite)
        self.ComboBoxSite = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBoxSite.setObjectName("ComboBoxSite")
        self.ComboBoxSite.addItem("")
        self.ComboBoxSite.addItem("")
        self.ComboBoxSite.addItem("")
        self.horizontalLayout.addWidget(self.ComboBoxSite)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.BushButtonSave = QtWidgets.QPushButton(self.centralwidget)
        self.BushButtonSave.setObjectName("BushButtonSave")
        self.gridLayout_3.addWidget(self.BushButtonSave, 9, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.LabelNameExcelFile = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelNameExcelFile.setFont(font)
        self.LabelNameExcelFile.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelNameExcelFile.setObjectName("LabelNameExcelFile")
        self.horizontalLayout_7.addWidget(self.LabelNameExcelFile)
        self.LineEditNameExcelFile = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEditNameExcelFile.setObjectName("LineEditNameExcelFile")
        self.horizontalLayout_7.addWidget(self.LineEditNameExcelFile)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LabelCaptcha = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelCaptcha.setFont(font)
        self.LabelCaptcha.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelCaptcha.setObjectName("LabelCaptcha")
        self.horizontalLayout_5.addWidget(self.LabelCaptcha)
        self.SpinBoxCaptcha = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinBoxCaptcha.setObjectName("SpinBoxCaptha")
        self.horizontalLayout_5.addWidget(self.SpinBoxCaptcha)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.LabelBypassingCapthas = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelBypassingCapthas.setFont(font)
        self.LabelBypassingCapthas.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelBypassingCapthas.setObjectName("LabelBypassingCapthas")
        self.horizontalLayout_6.addWidget(self.LabelBypassingCapthas)
        self.ComboBoxBypassingCaptchas = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBoxBypassingCaptchas.setObjectName("ComboBoxBypassingCapthas")
        self.ComboBoxBypassingCaptchas.addItem("")
        self.ComboBoxBypassingCaptchas.addItem("")
        self.ComboBoxBypassingCaptchas.addItem("")
        self.ComboBoxBypassingCaptchas.addItem("")
        self.horizontalLayout_6.addWidget(self.ComboBoxBypassingCaptchas)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LabelDelayError = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LabelDelayError.setFont(font)
        self.LabelDelayError.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelDelayError.setObjectName("LabelDelayError")
        self.horizontalLayout_2.addWidget(self.LabelDelayError)
        self.SpinBoxDelayError = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinBoxDelayError.setObjectName("SpinBoxDelayError")
        self.horizontalLayout_2.addWidget(self.SpinBoxDelayError)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.LabelListLinks = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LabelListLinks.setFont(font)
        self.LabelListLinks.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelListLinks.setObjectName("LabelListLinks")
        self.horizontalLayout_8.addWidget(self.LabelListLinks)
        self.ListWidgetListLinks = QtWidgets.QListWidget(self.centralwidget)
        self.ListWidgetListLinks.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ListWidgetListLinks.setObjectName("ListWidgetListLinks")
        self.horizontalLayout_8.addWidget(self.ListWidgetListLinks)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 8, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ДОБАВЛЕНИЕ САЙТА"))
        self.LabelNameSite.setText(_translate("MainWindow", "Выбор сайта"))
        self.ComboBoxSite.setItemText(0, _translate("MainWindow", "None"))
        self.ComboBoxSite.setItemText(1, _translate("MainWindow", "Leroy Merlin"))
        self.ComboBoxSite.setItemText(2, _translate("MainWindow", "Lenta"))
        self.BushButtonSave.setText(_translate("MainWindow", "Сохранить"))
        self.LabelNameExcelFile.setText(_translate("MainWindow", "Название итогового excel файла"))
        self.LabelCaptcha.setText(_translate("MainWindow", "Задержка между объявлениями"))
        self.LabelBypassingCapthas.setText(_translate("MainWindow", "При появлении капчи использывать"))
        self.ComboBoxBypassingCaptchas.setItemText(0, _translate("MainWindow", "None"))
        self.ComboBoxBypassingCaptchas.setItemText(1, _translate("MainWindow", "Anti-captcha"))
        self.ComboBoxBypassingCaptchas.setItemText(2, _translate("MainWindow", "Proxy"))
        self.ComboBoxBypassingCaptchas.setItemText(3, _translate("MainWindow", "Anti-Captcha and Proxy"))
        self.LabelDelayError.setText(_translate("MainWindow", "Задержка при появление ошибки"))
        self.LabelListLinks.setText(_translate("MainWindow", "Список ссылок"))
