# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle("Парсинг")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_list_links = QtWidgets.QLabel(self.centralwidget)
        self.label_list_links.setMinimumSize(QtCore.QSize(200, 30))
        self.label_list_links.setAlignment(QtCore.Qt.AlignCenter)
        self.label_list_links.setObjectName("label_list_links")
        self.horizontalLayout_10.addWidget(self.label_list_links)
        self.listWidget_list_links = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_list_links.setMaximumSize(QtCore.QSize(16777214, 150))
        self.listWidget_list_links.setMovement(QtWidgets.QListView.Static)
        self.listWidget_list_links.setObjectName("listWidget_list_links")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_list_links.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_list_links.addItem(item)
        self.horizontalLayout_10.addWidget(self.listWidget_list_links)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 8, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 12, 0, 1, 1)
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setMinimumSize(QtCore.QSize(0, 30))
        self.label_name.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_name.setScaledContents(False)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setWordWrap(False)
        self.label_name.setOpenExternalLinks(False)
        self.label_name.setObjectName("label_name")
        self.gridLayout_3.addWidget(self.label_name, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_add_url = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_url.setObjectName("button_add_url")
        self.horizontalLayout_4.addWidget(self.button_add_url)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout_4.addWidget(self.button_save)
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setObjectName("button_start")
        self.horizontalLayout_4.addWidget(self.button_start)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 10, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_delay_between_pages = QtWidgets.QLabel(self.centralwidget)
        self.label_delay_between_pages.setMinimumSize(QtCore.QSize(200, 30))
        self.label_delay_between_pages.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay_between_pages.setObjectName("label_delay_between_pages")
        self.horizontalLayout_5.addWidget(self.label_delay_between_pages)
        self.spinBox_delay_between_pages = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_delay_between_pages.setObjectName("spinBox_delay_between_pages")
        self.horizontalLayout_5.addWidget(self.spinBox_delay_between_pages)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_file_name = QtWidgets.QLabel(self.centralwidget)
        self.label_file_name.setMinimumSize(QtCore.QSize(200, 30))
        self.label_file_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_file_name.setObjectName("label_file_name")
        self.horizontalLayout_9.addWidget(self.label_file_name)
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.horizontalLayout_9.addWidget(self.lineEdit_file_name)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_delay_between_ads = QtWidgets.QLabel(self.centralwidget)
        self.label_delay_between_ads.setMinimumSize(QtCore.QSize(200, 30))
        self.label_delay_between_ads.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay_between_ads.setObjectName("label_delay_between_ads")
        self.horizontalLayout.addWidget(self.label_delay_between_ads)
        self.spinBox_delay_between_ads = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_delay_between_ads.setObjectName("spinBox_delay_between_ads")
        self.horizontalLayout.addWidget(self.spinBox_delay_between_ads)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_delay_after_error = QtWidgets.QLabel(self.centralwidget)
        self.label_delay_after_error.setMinimumSize(QtCore.QSize(200, 30))
        self.label_delay_after_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay_after_error.setObjectName("label_delay_after_error")
        self.horizontalLayout_7.addWidget(self.label_delay_after_error)
        self.spinBox_delay_after_error = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_delay_after_error.setObjectName("spinBox_delay_after_error")
        self.horizontalLayout_7.addWidget(self.spinBox_delay_after_error)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_working_with_captchas = QtWidgets.QLabel(self.centralwidget)
        self.label_working_with_captchas.setMinimumSize(QtCore.QSize(200, 30))
        self.label_working_with_captchas.setAlignment(QtCore.Qt.AlignCenter)
        self.label_working_with_captchas.setObjectName("label_working_with_captchas")
        self.horizontalLayout_8.addWidget(self.label_working_with_captchas)
        # self.comboBox_working_with_captchas = QtWidgets.QComboBox(self.centralwidget)
        # self.comboBox_working_with_captchas.setObjectName("comboBox_working_with_captchas")
        # self.comboBox_working_with_captchas.addItem("")
        # self.comboBox_working_with_captchas.addItem("")
        # self.comboBox_working_with_captchas.addItem("")
        # self.comboBox_working_with_captchas.addItem("")
        # self.horizontalLayout_8.addWidget(self.comboBox_working_with_captchas)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 11, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_list_links.setText(_translate("MainWindow", "Список ссылок"))
        __sortingEnabled = self.listWidget_list_links.isSortingEnabled()
        self.listWidget_list_links.setSortingEnabled(False)
        item = self.listWidget_list_links.item(0)
        item.setText(_translate("MainWindow", "https://leroymerlin.ru/search/?q=шкаф"))
        item = self.listWidget_list_links.item(1)
        item.setText(_translate("MainWindow", "https://leroymerlin.ru/search/?q=лион&family=garderobnye-sistemy-panelnye-201709&suggest=true"))
        self.spinBox_delay_between_ads.setMaximum(1000)
        self.spinBox_delay_between_pages.setMaximum(1000)
        self.spinBox_delay_after_error.setMaximum(1000)
        self.listWidget_list_links.setSortingEnabled(__sortingEnabled)
        self.label_name.setText(_translate("MainWindow", "Парсер сайтов"))
        self.button_add_url.setText(_translate("MainWindow", "Добавить ссылку"))
        self.button_save.setText(_translate("MainWindow", "Сохранить"))
        self.button_start.setText(_translate("MainWindow", "Запустить"))
        self.label_delay_between_pages.setText(_translate("MainWindow", "Задержка между страницами"))
        self.label_file_name.setText(_translate("MainWindow", "Название файла"))
        self.lineEdit_file_name.setText(_translate("MainWindow", "sample.xlsx"))
        self.label_delay_between_ads.setText(_translate("MainWindow", "Задержка между объявлениями"))
        self.label_delay_after_error.setText(_translate("MainWindow", "Задержка при появлении ошибки"))
        # self.label_working_with_captchas.setText(_translate("MainWindow", "При появлении капчи использовать"))
        # self.comboBox_working_with_captchas.setItemText(0, _translate("MainWindow", "None"))
        # self.comboBox_working_with_captchas.setItemText(1, _translate("MainWindow", "Антикапча"))
        # self.comboBox_working_with_captchas.setItemText(2, _translate("MainWindow", "Прокси"))
        # self.comboBox_working_with_captchas.setItemText(3, _translate("MainWindow", "Прокси и Антикапча"))


class Ui_AddUrl(QtWidgets.QDialog):

    ready_url = ''

    def __init__(self, parent=False):
        super(Ui_AddUrl, self).__init__(parent)
        self.setWindowTitle("Добавить ссылку")
        self.resize(20, 20)

        self.horizontalLayout = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout.setObjectName("verticalLayout")

        self.label_name_url = QtWidgets.QLabel(self)
        self.label_name_url.setText("Введите ссылку")

        self.lineEdit_url = QtWidgets.QLineEdit(self)

        self.pushButton_add_url = QtWidgets.QPushButton(self)
        self.pushButton_add_url.setObjectName("pushButton_add_url")
        self.pushButton_add_url.setText("Добавить ссылку")
        self.pushButton_add_url.clicked.connect(self.__add_url)

        self.horizontalLayout.addWidget(self.label_name_url)
        self.horizontalLayout.addWidget(self.lineEdit_url)
        self.horizontalLayout.addWidget(self.pushButton_add_url)

    def __add_url(self):
        self.ready_url = self.lineEdit_url.text()
        self.close()
